language: elixir
sudo: required
services: docker
elixir:
  - 1.3

before_install:
  - docker run --name neo4j -d -p 7687:7687 -e 'NEO4J_AUTH=neo4j/password' neo4j:3.0.6
  - docker logs -f neo4j | sed /Bolt\ enabled/q
